### ISSUE TITLE
Exception on get_value_by_xpath after urlencode was added

### ISSUE THREAD

**Issue by arunpoudel** [iMicknl/python-sagemcom-api#33]
## Versions

| Key               | Value |
| ----------------- | ----- |
| Package version   |   v1.0.3    |
| Python Version    |    3.8.7   |
| F@st Router Model |  F@st 3890V3    |

## Describe the bug
As of this commit, https://github.com/iMicknl/python-sagemcom-api/commit/465347ad99d8e74c81a8f534ffaf1bc69cb68e41
The code crashes when running function get_value_by_xpath

Here is a traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/urllib/parse.py", line 908, in urlencode
    raise TypeError
TypeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/sagemcom_fast/__init__.py", line 109, in async_setup_entry
    gateway = await client.get_device_info()
  File "/usr/local/lib/python3.8/site-packages/sagemcom_api/client.py", line 327, in get_device_info
    data = await self.get_value_by_xpath("Device/DeviceInfo")
  File "/usr/local/lib/python3.8/site-packages/sagemcom_api/client.py", line 293, in get_value_by_xpath
    "xpath": urllib.parse.urlencode(xpath),
  File "/usr/local/lib/python3.8/urllib/parse.py", line 915, in urlencode
    raise TypeError("not a valid non-string sequence "
  File "/usr/local/lib/python3.8/urllib/parse.py", line 908, in urlencode
    raise TypeError
TypeError: not a valid non-string sequence or mapping object

```

[bug]

**Comment by arunpoudel** [comment]
I am not a day to day python user, but as per quick search on the internet `urllib.parse.urlencode` only works on dictionary, but we are passing string.

**Comment by arunpoudel** [comment]
Reading through the issue #29  that prompted the change it seems that we were supposed to use `quote` function instead of `parse`
