### ISSUE TITLE
Unsupported model: F@ST F5359 / KPN Box 12

### ISSUE THREAD

**Issue by geert36** [iMicknl/python-sagemcom-api#38]
I recently got the Sagemcom box F@ST F5359. It is the new modem distributed by KPN known as the Box 12.

I tried to get some more information with executing `$.xmo.getValuesTree("Device/DeviceInfo");` in the web console, this results in nothing.

Is it possible to support this device? Please let me know if you need more information.
I want to use it for presence detection in Home Assistant.

## Model information

| Key                      | Value |
| ------------------------ | ----- |
| Model name               | F@ST F5359 |
| Hardware Version         | 1.0 |
| Software Version         | SGEJ10000310 |

**Comment by iMicknl** [comment]
When you are logged in, do you see any XHR requests in DevTools -> Network? See https://stackoverflow.com/questions/1820927/request-monitoring-in-chrome.

**Comment by geert36** [comment]
Yes, I see json-req:
`vendor.js?abc2f5c9832d68eb:3 XHR finished loading: POST "https://mijnmodem.kpn/cgi/json-req".`

**Comment by iMicknl** [comment]
@geert36 I am not sure how to debug this, do you have some Python knowledge? It seems that you have the JSON-REQ API, however it could be that you need `mijnmodem.kpn` instead of the IP address. However, by default it will communicate via HTTP...

Have you tried setting it up in Home Assistant or directly via the Python test script? What kind of error do you see in your logs.

**Comment by geert36** [comment]
I don't have any Python knowledge. But if is just running some code, I think I can manage it.

Yes, already tried to set it up in Home Assistant. I tried `mijnmodem.kpn` and the default gateway adress, both encryption methods. All with the same result: "Request timed-out. This is mainly caused by selection of the wrong encryption method"

**Comment by iMicknl** [comment]
If you login, will it do a HTTPS request to `https://mijnmodem.kpn/cgi/json-req` as well? It would require some code changes to support this perhaps.

**Comment by geert36** [comment]
Yes, correct, `https://mijnmodem.kpn/cgi/json-req` is requested.

**Comment by iMicknl** [comment]
@geert36 could you give https://github.com/iMicknl/ha-sagemcom-fast/archive/refs/heads/feature/add_ssl_support.zip a try? Extract this file and place `custom_components/sagemcom_fast` in your `custom_components` folder. (overwrite the previous one).

**Comment by geert36** [comment]
Tried with the new files, but get the following error:
`__init__() got an unexpected keyword argument 'ssl'
Traceback (most recent call last):
  File "/config/custom_components/sagemcom_fast/config_flow.py", line 70, in async_step_user
    return await self.async_validate_input(user_input)
  File "/config/custom_components/sagemcom_fast/config_flow.py", line 47, in async_validate_input
    async with SagemcomClient(
  File "/usr/local/lib/python3.8/site-packages/sagemcom_api/client.py", line 80, in __init__
    else ClientSession(
TypeError: __init__() got an unexpected keyword argument 'ssl'`

**Comment by iMicknl** [comment]
@geert36 it should install the development version, that includes this fix, however it seems that this is not working in your install. I will see if I can prepare it in another way..

**Comment by iMicknl** [comment]
@geert36 could you give it a new try? Just download the same zip folder again and repeat the same steps :)

**Comment by geert36** [comment]
Hi Mick, thanks for the update. This one works with the SHA512 encryption! I didn't check any of the check boxes (there is no text behind the check boxes). 
So now the integration is added in HA, but the next error appeared:
`{'code': 16777225, 'description': 'XMO_MAX_SESSION_COUNT_ERR'}
Traceback (most recent call last):
  File "/config/custom_components/sagemcom_fast/config_flow.py", line 81, in async_step_user
    return await self.async_validate_input(user_input)
  File "/config/custom_components/sagemcom_fast/config_flow.py", line 66, in async_validate_input
    await client.login()
  File "/usr/local/lib/python3.8/site-packages/sagemcom_api/client.py", line 271, in login
    response = await self.__api_request_async([actions], True)
  File "/usr/local/lib/python3.8/site-packages/sagemcom_api/client.py", line 241, in __api_request_async
    raise UnknownException(action_error)
sagemcom_api.exceptions.UnknownException: {'code': 16777225, 'description': 'XMO_MAX_SESSION_COUNT_ERR'}
`

**Comment by iMicknl** [comment]
@geert36 that is weird, it should only work with the SSL check box selected. What did you fill in as host? Could you reboot and try it again + share a screenshot of your the 'new integration' form popup?

I will make sure we catch `XMO_MAX_SESSION_COUNT_ERR`, I hadn't seen that before. But it seems that you can only have one login session at the same time... Can you add multiple users?
